"""empty message

Revision ID: 43e44cb6376c
Revises: bc511c863bd6
Create Date: 2022-09-14 07:01:51.922730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e44cb6376c'
down_revision = 'bc511c863bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('currency', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'currency')
    # ### end Alembic commands ###
