"""empty message

Revision ID: 0b7139ab4484
Revises: e6a237801c7d
Create Date: 2022-09-11 21:27:31.600174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7139ab4484'
down_revision = 'e6a237801c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad', 'title',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.alter_column('ad', 'currency',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('ad', 'seller',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad', 'seller',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('ad', 'currency',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('ad', 'title',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    # ### end Alembic commands ###
