"""empty message

Revision ID: 83da4b1faaaa
Revises: 0b7139ab4484
Create Date: 2022-09-11 23:46:17.674545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83da4b1faaaa'
down_revision = '0b7139ab4484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ad', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ad', type_='unique')
    # ### end Alembic commands ###
