"""empty message

Revision ID: c7c7548597b4
Revises: 83da4b1faaaa
Create Date: 2022-09-12 08:17:26.907855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c7548597b4'
down_revision = '83da4b1faaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ad_title_key', 'ad', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ad_title_key', 'ad', ['title'])
    # ### end Alembic commands ###
