"""empty message

Revision ID: e6a237801c7d
Revises: 45cebc3b05ba
Create Date: 2022-09-11 19:56:45.324735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a237801c7d'
down_revision = '45cebc3b05ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ad_title', table_name='ad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ad_title', 'ad', ['title'], unique=False)
    # ### end Alembic commands ###
